#!/bin/bash

MAIN="vegastrike"
DATADIR="/usr/share/$MAIN"
TARGET="$HOME/.$MAIN"
TOCOPY="ls /usr/share/vegastrike/.vegastrike-0.5.0/*"

if [ ! -e "$TARGET" ]; then
        mkdir "$TARGET"
fi

for f in $TOCOPY; do
        if [ ! -e "$TARGET/$f" ] ; then
                cp -R "$f" "$TARGET/"
        fi
done

exec $MAIN.bin