#!/bin/bash

MAIN="vegastrike"
DATADIR="/usr/share/$MAIN"
TARGET="$HOME/.$MAIN"
TOCOPY="setup.config vegastrike.config"

if [ ! -e "$TARGET" ]; then
        mkdir "$TARGET"
fi

for f in $TOCOPY; do
        if [ ! -e "$TARGET/$f" ] ; then
                cp -R "$DATADIR/$f" "$TARGET/"
        fi
done

cd "$TARGET"

exec vssetup.bin