#! /bin/bash
Encoding=UTF-8
pisi ar pisilife https://github.com/pisilinux/pisilife/raw/master/pisi-index.xml.xz
rm /tmp/pikap.txt
exec pisi ls | cut -f 1 -d' '>> /tmp/pikap.txt


export MAIN_DIALOG='
<window window_position="1" title="PiKaP:Pisi Linux Kaynak Paket İnşa Aracı">

<vbox>
  <tree>
        <label>Paket Adı</label>
        <input>cat /tmp/pikap.txt</input>
        <height>200</height><width>600</width>
        <variable>TREE1</variable>
        <action>pisi info $TREE1 | zenity --text-info --width=600 --height=500 --title $"Detaylar" &</action>
  </tree>
  <hbox>
  <frame>
    <pixmap>
         <input file>/home/erturk/image3457.png</input>
    </pixmap>
   </frame>
       <frame>
      <vbox>
    <button>
         <input file stock="gtk-apply"></input>
         <label>Yükle</label>
         <action>xfce4-terminal -H -x pisi em $TREE1 &</action>
   </button>
        <button>
        <input file stock="gtk-close"></input>
        <label>Kaldır</label>
        <action>xfce4-terminal -H -x pisi rm $TREE1 &</action>
   </button>
   <button>
        <label>Geçmiş</label>
        <input file stock="gtk-info"></input>
        <action>pisi hs | zenity --text-info --width=800 --height=400 --title $"Yükleme Geçmişi" &</action>
    </button>
     </vbox>
    </frame>
  </hbox>
</vbox>
</window>
'

gtkdialog --program=MAIN_DIALOG