#!/bin/bash

# Skype does not work well with newer version of GSPCA Webcams driver
# (Linux Kernel >=2.6.27), possible workaround.
# http://share.skype.com/sites/garage/2010/01/skype_21_beta_2_aka_talking_sc.html


if [[ -e "/usr/lib32/libv4l/v4l2convert.so" ]]; then
        export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}/usr/lib32/libv4l/v4l2convert.so"
fi

if [[ -e "/usr/lib32/libQtWebKit.so.4" ]]; then
        export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}/usr/lib32/libQtWebKit.so.4"
fi

PULSE_LATENCY_MSEC=30 exec "/usr/share/skype/skype" "$@"

