# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yali/gui/Ui/checkcdwidget.ui'
#
# Created: Mon Nov 24 20:29:48 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

import gettext
__trans = gettext.translation('yali', fallback=True)
i18n = __trans.ugettext
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CheckCDWidget(object):
    def setupUi(self, CheckCDWidget):
        CheckCDWidget.setObjectName(_fromUtf8("CheckCDWidget"))
        CheckCDWidget.resize(635, 490)
        CheckCDWidget.setWindowTitle(_fromUtf8(""))
        CheckCDWidget.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(CheckCDWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(CheckCDWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(600, 250))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame.setStyleSheet(_fromUtf8("#frame{background-color: rgba(0,0,0,100)}"))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(-1, 20, -1, 20)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.pix = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pix.sizePolicy().hasHeightForWidth())
        self.pix.setSizePolicy(sizePolicy)
        self.pix.setLineWidth(0)
        self.pix.setPixmap(QtGui.QPixmap(_fromUtf8(":/gui/pics/media-optical.png")))
        self.pix.setAlignment(QtCore.Qt.AlignCenter)
        self.pix.setWordWrap(False)
        self.pix.setObjectName(_fromUtf8("pix"))
        self.gridLayout_3.addWidget(self.pix, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.checkLabel = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkLabel.sizePolicy().hasHeightForWidth())
        self.checkLabel.setSizePolicy(sizePolicy)
        self.checkLabel.setMinimumSize(QtCore.QSize(350, 0))
        self.checkLabel.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkLabel.setFont(font)
        self.checkLabel.setStyleSheet(_fromUtf8(""))
        self.checkLabel.setLineWidth(0)
        self.checkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.checkLabel.setWordWrap(True)
        self.checkLabel.setMargin(0)
        self.checkLabel.setObjectName(_fromUtf8("checkLabel"))
        self.verticalLayout.addWidget(self.checkLabel)
        self.validationFailBox = QtGui.QGroupBox(self.frame)
        self.validationFailBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.validationFailBox.setStyleSheet(_fromUtf8("border:0px"))
        self.validationFailBox.setTitle(_fromUtf8(""))
        self.validationFailBox.setFlat(True)
        self.validationFailBox.setObjectName(_fromUtf8("validationFailBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.validationFailBox)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_7 = QtGui.QLabel(self.validationFailBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setLineWidth(0)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/gui/pics/dialog-error.png")))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.validationFailBox)
        self.label_8.setLineWidth(0)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.validationFailBox)
        self.validationSucceedBox = QtGui.QGroupBox(self.frame)
        self.validationSucceedBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.validationSucceedBox.setStyleSheet(_fromUtf8("border:0px"))
        self.validationSucceedBox.setTitle(_fromUtf8(""))
        self.validationSucceedBox.setFlat(True)
        self.validationSucceedBox.setObjectName(_fromUtf8("validationSucceedBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.validationSucceedBox)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_2 = QtGui.QLabel(self.validationSucceedBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setLineWidth(0)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/gui/pics/task-complete.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.validationSucceedBox)
        self.label.setLineWidth(0)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.validationSucceedBox)
        self.validationBox = QtGui.QGroupBox(self.frame)
        self.validationBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.validationBox.setStyleSheet(_fromUtf8("#validationBox{border: 0px;}"))
        self.validationBox.setTitle(_fromUtf8(""))
        self.validationBox.setFlat(True)
        self.validationBox.setObjectName(_fromUtf8("validationBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.validationBox)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(self.validationBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.checkButton = QtGui.QPushButton(self.validationBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkButton.sizePolicy().hasHeightForWidth())
        self.checkButton.setSizePolicy(sizePolicy)
        self.checkButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkButton.setStyleSheet(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/gui/pics/task-accepted.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkButton.setIcon(icon)
        self.checkButton.setDefault(True)
        self.checkButton.setFlat(False)
        self.checkButton.setObjectName(_fromUtf8("checkButton"))
        self.horizontalLayout.addWidget(self.checkButton)
        self.verticalLayout.addWidget(self.validationBox)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(CheckCDWidget)
        QtCore.QMetaObject.connectSlotsByName(CheckCDWidget)

    def retranslateUi(self, CheckCDWidget):
        self.checkLabel.setText(i18n("You can validate the integrity of the installation packages. Although this is an optional step, we highly recommend to do the validation in order to avoid any possible errors during the installation process."))
        self.label_8.setText(i18n("Validation failed"))
        self.label.setText(i18n("Validation succeeded"))
        self.checkButton.setText(i18n("Validate"))

