#!/bin/bash
export CHROME_DEVEL_SANDBOX=/opt/maxthon/maxthon_sandbox
export MAXTHON_PATH="`readlink -f "$0"`"

HERE="`dirname "$MAXTHON_PATH"`"

if ! which xdg-settings &> /dev/null; then
  # Old xdg utilities. Prepend $HERE to $PATH to use ours instead.
  export PATH="$HERE:$PATH"
else
  xdg_app_dir="${XDG_DATA_HOME:-$HOME/.local/share/applications}"
  mkdir -p "$xdg_app_dir"
  [ -f "$xdg_app_dir/mimeapps.list" ] || touch "$xdg_app_dir/mimeapps.list"
fi

if [[ -n "$LD_LIBRARY_PATH" ]]; then
  LD_LIBRARY_PATH="$HERE:$HERE/lib:$LD_LIBRARY_PATH"
else
  LD_LIBRARY_PATH="$HERE:$HERE/lib"
fi
export LD_LIBRARY_PATH
SWITCH="--ppapi-flash-path="
VERSION_SWITCH="--ppapi-flash-version="
STABLE="/opt/google/chrome/PepperFlash/libpepflashplayer.so"
BETA="/opt/google/chrome-beta/PepperFlash/libpepflashplayer.so"
DEV="/opt/google/chrome-unstable/PepperFlash/libpepflashplayer.so"
NONFREE="/usr/lib/chromium-browser/PepperFlash/libpepflashplayer.so"

if [[ -f $STABLE ]]; then
	pepper="$SWITCH$STABLE"
	flash_path="$STABLE"
elif [[ -f $BETA ]]; then
	pepper="$SWITCH$BETA"
	flash_path="$BETA"
elif [[ -f $DEV ]]; then
	pepper="$SWITCH$DEV"
	flash_path="$DEV"
elif [[ -f $NONFREE ]]; then
	pepper="$SWITCH$NONFREE"
	flash_path=$NONFREE
fi

if [[ -n $pepper ]]; then
	pepper_version=$VERSION_SWITCH$(strings $flash_path |grep LNX|tr , .|grep -o "[0-9\.]*")
fi
exec -a $0 /opt/maxthon/maxthon $pepper $pepper_version "$@"

